### ISSUE TITLE
Displaying blank while reading ordinary bitmaps in Ver5 IMGs...

### ISSUE THREAD

**Issue by No5972** [Kritsu/ExtractorSharp#1] opened 2018-03-02 18:33 UTC
Ordinary bitmaps are also in Ver5 IMGs. Therefore it is also needed to read and extract the ordinary bitmaps in Ver5 IMGs... And when reading ordinary bitmaps, it displays blank.
There are some existing NPK files that ordinary bitmaps are in the Ver 5 IMGs like:
sprite_interface2_window_title_accessory.NPK (CDNF, DFOG, etc)
sprite_interface2_cs_shop.NPK (KDNF only)

**Comment by chizukicn** [comment] 2018-03-03 12:08
这个问题是因为Ver5的IMG中存在ARGB_8888的贴图,这是最近才发现的。过去我认为Ver5只有ARGB_1555的。代码上已经修复了这个问题，但是发行版预计得等一段时间了。

The problem is because of the ARGB_8888 mapping in Ver5's IMG, which was recently discovered. I used to think that Ver5 was only ARGB_1555. The problem has been fixed on the code, but the release is expected to wait for some time.(from Baidu Translate.)

**Closed as completed** 2018-03-11 05:45 UTC
